<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE HealthData [
<!-- HealthKit Export Version: 11 -->
<!ELEMENT HealthData (ExportDate,Me,(Record|Correlation|Workout|ActivitySummary|ClinicalRecord)*)>
<!ATTLIST HealthData
  locale CDATA #REQUIRED
>
<!ELEMENT ExportDate EMPTY>
<!ATTLIST ExportDate
  value CDATA #REQUIRED
>
<!ELEMENT Me EMPTY>
<!ATTLIST Me
  HKCharacteristicTypeIdentifierDateOfBirth         CDATA #REQUIRED
  HKCharacteristicTypeIdentifierBiologicalSex       CDATA #REQUIRED
  HKCharacteristicTypeIdentifierBloodType           CDATA #REQUIRED
  HKCharacteristicTypeIdentifierFitzpatrickSkinType CDATA #REQUIRED
>
<!ELEMENT Record ((MetadataEntry|HeartRateVariabilityMetadataList)*)>
<!ATTLIST Record
  type          CDATA #REQUIRED
  unit          CDATA #IMPLIED
  value         CDATA #IMPLIED
  sourceName    CDATA #REQUIRED
  sourceVersion CDATA #IMPLIED
  device        CDATA #IMPLIED
  creationDate  CDATA #IMPLIED
  startDate     CDATA #REQUIRED
  endDate       CDATA #REQUIRED
>
<!-- Note: Any Records that appear as children of a correlation also appear as top-level records in this document. -->
<!ELEMENT Correlation ((MetadataEntry|Record)*)>
<!ATTLIST Correlation
  type          CDATA #REQUIRED
  sourceName    CDATA #REQUIRED
  sourceVersion CDATA #IMPLIED
  device        CDATA #IMPLIED
  creationDate  CDATA #IMPLIED
  startDate     CDATA #REQUIRED
  endDate       CDATA #REQUIRED
>
<!ELEMENT Workout ((MetadataEntry|WorkoutEvent|WorkoutRoute)*)>
<!ATTLIST Workout
  workoutActivityType   CDATA #REQUIRED
  duration              CDATA #IMPLIED
  durationUnit          CDATA #IMPLIED
  totalDistance         CDATA #IMPLIED
  totalDistanceUnit     CDATA #IMPLIED
  totalEnergyBurned     CDATA #IMPLIED
  totalEnergyBurnedUnit CDATA #IMPLIED
  sourceName            CDATA #REQUIRED
  sourceVersion         CDATA #IMPLIED
  device                CDATA #IMPLIED
  creationDate          CDATA #IMPLIED
  startDate             CDATA #REQUIRED
  endDate               CDATA #REQUIRED
>
<!ELEMENT WorkoutEvent EMPTY>
<!ATTLIST WorkoutEvent
  type         CDATA #REQUIRED
  date         CDATA #REQUIRED
  duration     CDATA #IMPLIED
  durationUnit CDATA #IMPLIED
>
<!ELEMENT WorkoutRoute ((MetadataEntry|FileReference)*)>
<!ATTLIST WorkoutRoute
  sourceName    CDATA #REQUIRED
  sourceVersion CDATA #IMPLIED
  device        CDATA #IMPLIED
  creationDate  CDATA #IMPLIED
  startDate     CDATA #REQUIRED
  endDate       CDATA #REQUIRED
>
<!ELEMENT FileReference EMPTY>
<!ATTLIST FileReference
  path CDATA #REQUIRED
>
<!ELEMENT ActivitySummary EMPTY>
<!ATTLIST ActivitySummary
  dateComponents           CDATA #IMPLIED
  activeEnergyBurned       CDATA #IMPLIED
  activeEnergyBurnedGoal   CDATA #IMPLIED
  activeEnergyBurnedUnit   CDATA #IMPLIED
  appleMoveTime            CDATA #IMPLIED
  appleMoveTimeGoal        CDATA #IMPLIED
  appleExerciseTime        CDATA #IMPLIED
  appleExerciseTimeGoal    CDATA #IMPLIED
  appleStandHours          CDATA #IMPLIED
  appleStandHoursGoal      CDATA #IMPLIED
>
<!ELEMENT MetadataEntry EMPTY>
<!ATTLIST MetadataEntry
  key   CDATA #REQUIRED
  value CDATA #REQUIRED
>
<!-- Note: Heart Rate Variability records captured by Apple Watch may include an associated list of instantaneous beats-per-minute readings. -->
<!ELEMENT HeartRateVariabilityMetadataList (InstantaneousBeatsPerMinute*)>
<!ELEMENT InstantaneousBeatsPerMinute EMPTY>
<!ATTLIST InstantaneousBeatsPerMinute
  bpm  CDATA #REQUIRED
  time CDATA #REQUIRED
>
<!ELEMENT ClinicalRecord EMPTY>
<!ATTLIST ClinicalRecord
  type              CDATA #REQUIRED
  identifier        CDATA #REQUIRED
  sourceName        CDATA #REQUIRED
  sourceURL         CDATA #REQUIRED
  fhirVersion       CDATA #REQUIRED
  receivedDate      CDATA #REQUIRED
  resourceFilePath  CDATA #REQUIRED
>
<!ELEMENT Audiogram EMPTY>
<!ATTLIST Audiogram
  type          CDATA #REQUIRED
  sourceName    CDATA #REQUIRED
  sourceVersion CDATA #IMPLIED
  device        CDATA #IMPLIED
  creationDate  CDATA #IMPLIED
  startDate     CDATA #REQUIRED
  endDate       CDATA #REQUIRED
>
<!ELEMENT SensitivityPoint EMPTY>
<!ATTLIST SensitivityPoint
  frequencyValue   CDATA #REQUIRED
  frequencyUnit    CDATA #REQUIRED
  leftEarValue     CDATA #IMPLIED
  leftEarUnit      CDATA #IMPLIED
  rightEarValue    CDATA #IMPLIED
  rightEarUnit     CDATA #IMPLIED
>
]>
<HealthData locale="en_RS">
 <ExportDate value="2022-03-25 15:20:29 -0700"/>
 <Me HKCharacteristicTypeIdentifierDateOfBirth="1900-01-01" HKCharacteristicTypeIdentifierBiologicalSex="HKBiologicalSexNotSet" HKCharacteristicTypeIdentifierBloodType="HKBloodTypeNotSet" HKCharacteristicTypeIdentifierFitzpatrickSkinType="HKFitzpatrickSkinTypeNotSet" HKCharacteristicTypeIdentifierCardioFitnessMedicationsUse="Rusty Iron"/>
 <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="Health" sourceVersion="14.0.1" unit="count" creationDate="2020-09-30 21:10:57 -0700" startDate="2020-09-30 21:10:00 -0700" endDate="2020-09-30 21:10:00 -0700" value="25.1">
  <MetadataEntry key="HKWasUserEntered" value="1"/>
 </Record>
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Ferris’s Apple Watch" sourceVersion="7.0.1" device="&lt;&lt;HKDevice: 0x000000000g&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,2, software:7.0.1&gt;" unit="count/min" creationDate="2020-09-30 20:42:05 -0700" startDate="2020-09-30 20:41:03 -0700" endDate="2020-09-30 20:41:03 -0700" value="74.9268">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Ferris’s Apple Watch" sourceVersion="7.0.1" device="&lt;&lt;HKDevice: 0x000000000g&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,2, software:7.0.1&gt;" unit="count/min" creationDate="2020-09-30 20:53:17 -0700" startDate="2020-09-30 20:53:16 -0700" endDate="2020-09-30 20:53:16 -0700" value="80">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Ferris’s Apple Watch" sourceVersion="7.0.1" device="&lt;&lt;HKDevice: 0x000000000g&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,2, software:7.0.1&gt;" unit="count/min" creationDate="2020-09-30 20:53:22 -0700" startDate="2020-09-30 20:53:21 -0700" endDate="2020-09-30 20:53:21 -0700" value="81">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Ferris’s Apple Watch" sourceVersion="7.0.1" device="&lt;&lt;HKDevice: 0x000000000g&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,2, software:7.0.1&gt;" unit="count/min" creationDate="2020-09-30 20:53:27 -0700" startDate="2020-09-30 20:53:26 -0700" endDate="2020-09-30 20:53:26 -0700" value="78">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Ferris’s Apple Watch" sourceVersion="7.0.1" device="&lt;&lt;HKDevice: 0x000000000g&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,2, software:7.0.1&gt;" unit="count/min" creationDate="2020-09-30 20:53:32 -0700" startDate="2020-09-30 20:53:31 -0700" endDate="2020-09-30 20:53:31 -0700" value="79">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Ferris’s Apple Watch" sourceVersion="7.0.1" device="&lt;&lt;HKDevice: 0x000000000g&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,2, software:7.0.1&gt;" unit="count/min" creationDate="2020-09-30 20:53:37 -0700" startDate="2020-09-30 20:53:32 -0700" endDate="2020-09-30 20:53:32 -0700" value="79">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Ferris’s Apple Watch" sourceVersion="7.0.1" device="&lt;&lt;HKDevice: 0x000000000g&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,2, software:7.0.1&gt;" unit="count/min" creationDate="2020-09-30 20:53:42 -0700" startDate="2020-09-30 20:53:41 -0700" endDate="2020-09-30 20:53:41 -0700" value="76">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Ferris’s Apple Watch" sourceVersion="7.0.1" device="&lt;&lt;HKDevice: 0x000000000g&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,2, software:7.0.1&gt;" unit="count/min" creationDate="2020-09-30 20:54:00 -0700" startDate="2020-09-30 20:53:59 -0700" endDate="2020-09-30 20:53:59 -0700" value="78">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Ferris’s Apple Watch" sourceVersion="7.0.1" device="&lt;&lt;HKDevice: 0x000000000g&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,2, software:7.0.1&gt;" unit="count/min" creationDate="2020-09-30 20:54:05 -0700" startDate="2020-09-30 20:54:04 -0700" endDate="2020-09-30 20:54:04 -0700" value="77">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Ferris’s Apple Watch" sourceVersion="7.0.1" device="&lt;&lt;HKDevice: 0x000000000g&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,2, software:7.0.1&gt;" unit="count/min" creationDate="2020-09-30 20:54:10 -0700" startDate="2020-09-30 20:54:07 -0700" endDate="2020-09-30 20:54:07 -0700" value="76">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Ferris’s Apple Watch" sourceVersion="7.0.1" device="&lt;&lt;HKDevice: 0x000000000g&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,2, software:7.0.1&gt;" unit="count/min" creationDate="2020-09-30 20:54:15 -0700" startDate="2020-09-30 20:54:14 -0700" endDate="2020-09-30 20:54:14 -0700" value="73">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Ferris’s Apple Watch" sourceVersion="7.0.1" device="&lt;&lt;HKDevice: 0x000000000g&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,2, software:7.0.1&gt;" unit="count/min" creationDate="2020-09-30 20:54:20 -0700" startDate="2020-09-30 20:54:19 -0700" endDate="2020-09-30 20:54:19 -0700" value="73">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Ferris’s Apple Watch" sourceVersion="7.0.1" device="&lt;&lt;HKDevice: 0x000000000g&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,2, software:7.0.1&gt;" unit="count/min" creationDate="2020-09-30 20:55:44 -0700" startDate="2020-09-30 20:55:29 -0700" endDate="2020-09-30 20:55:29 -0700" value="75">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Ferris’s Apple Watch" sourceVersion="7.0.1" device="&lt;&lt;HKDevice: 0x000000000g&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,2, software:7.0.1&gt;" unit="count/min" creationDate="2020-09-30 20:56:13 -0700" startDate="2020-09-30 20:56:13 -0700" endDate="2020-09-30 20:56:13 -0700" value="73">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Ferris’s Apple Watch" sourceVersion="7.0.1" device="&lt;&lt;HKDevice: 0x000000000g&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,2, software:7.0.1&gt;" unit="count/min" creationDate="2020-09-30 20:56:51 -0700" startDate="2020-09-30 20:55:49 -0700" endDate="2020-09-30 20:55:49 -0700" value="73.1429">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Ferris’s Apple Watch" sourceVersion="7.0.1" device="&lt;&lt;HKDevice: 0x000000000g&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,2, software:7.0.1&gt;" unit="count/min" creationDate="2020-09-30 20:58:50 -0700" startDate="2020-09-30 20:58:49 -0700" endDate="2020-09-30 20:58:49 -0700" value="69">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Ferris’s Apple Watch" sourceVersion="7.0.1" device="&lt;&lt;HKDevice: 0x000000000g&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,2, software:7.0.1&gt;" unit="count/min" creationDate="2020-09-30 20:58:50 -0700" startDate="2020-09-30 20:58:50 -0700" endDate="2020-09-30 20:58:50 -0700" value="68">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Ferris’s Apple Watch" sourceVersion="7.0.1" device="&lt;&lt;HKDevice: 0x000000000g&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,2, software:7.0.1&gt;" unit="count/min" creationDate="2020-09-30 20:58:52 -0700" startDate="2020-09-30 20:58:51 -0700" endDate="2020-09-30 20:58:51 -0700" value="67">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Ferris’s Apple Watch" sourceVersion="7.0.1" device="&lt;&lt;HKDevice: 0x000000000g&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,2, software:7.0.1&gt;" unit="count/min" creationDate="2020-09-30 20:58:52 -0700" startDate="2020-09-30 20:58:52 -0700" endDate="2020-09-30 20:58:52 -0700" value="67">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Ferris’s Apple Watch" sourceVersion="7.0.1" device="&lt;&lt;HKDevice: 0x000000000g&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,2, software:7.0.1&gt;" unit="count/min" creationDate="2020-09-30 20:58:54 -0700" startDate="2020-09-30 20:58:53 -0700" endDate="2020-09-30 20:58:53 -0700" value="68">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Ferris’s Apple Watch" sourceVersion="7.0.1" device="&lt;&lt;HKDevice: 0x000000000g&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,2, software:7.0.1&gt;" unit="count/min" creationDate="2020-09-30 20:58:54 -0700" startDate="2020-09-30 20:58:54 -0700" endDate="2020-09-30 20:58:54 -0700" value="70">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Ferris’s Apple Watch" sourceVersion="7.0.1" device="&lt;&lt;HKDevice: 0x000000000g&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,2, software:7.0.1&gt;" unit="count/min" creationDate="2020-09-30 20:58:56 -0700" startDate="2020-09-30 20:58:55 -0700" endDate="2020-09-30 20:58:55 -0700" value="69">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Ferris’s Apple Watch" sourceVersion="7.0.1" device="&lt;&lt;HKDevice: 0x000000000g&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,2, software:7.0.1&gt;" unit="count/min" creationDate="2020-09-30 20:58:56 -0700" startDate="2020-09-30 20:58:56 -0700" endDate="2020-09-30 20:58:56 -0700" value="69">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Ferris’s Apple Watch" sourceVersion="7.0.1" device="&lt;&lt;HKDevice: 0x000000000g&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,2, software:7.0.1&gt;" unit="count/min" creationDate="2020-09-30 20:58:58 -0700" startDate="2020-09-30 20:58:57 -0700" endDate="2020-09-30 20:58:57 -0700" value="69">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Ferris’s Apple Watch" sourceVersion="7.0.1" device="&lt;&lt;HKDevice: 0x000000000g&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,2, software:7.0.1&gt;" unit="count/min" creationDate="2020-09-30 20:58:58 -0700" startDate="2020-09-30 20:58:58 -0700" endDate="2020-09-30 20:58:58 -0700" value="69">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Ferris’s Apple Watch" sourceVersion="7.0.1" device="&lt;&lt;HKDevice: 0x000000000g&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,2, software:7.0.1&gt;" unit="count/min" creationDate="2020-09-30 20:59:00 -0700" startDate="2020-09-30 20:58:59 -0700" endDate="2020-09-30 20:58:59 -0700" value="70">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Ferris’s Apple Watch" sourceVersion="7.0.1" device="&lt;&lt;HKDevice: 0x000000000g&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,2, software:7.0.1&gt;" unit="count/min" creationDate="2020-09-30 20:59:00 -0700" startDate="2020-09-30 20:59:00 -0700" endDate="2020-09-30 20:59:00 -0700" value="71">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Ferris’s Apple Watch" sourceVersion="7.0.1" device="&lt;&lt;HKDevice: 0x000000000g&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,2, software:7.0.1&gt;" unit="count/min" creationDate="2020-09-30 20:59:02 -0700" startDate="2020-09-30 20:59:01 -0700" endDate="2020-09-30 20:59:01 -0700" value="71">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Ferris’s Apple Watch" sourceVersion="7.0.1" device="&lt;&lt;HKDevice: 0x000000000g&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,2, software:7.0.1&gt;" unit="count/min" creationDate="2020-09-30 20:59:02 -0700" startDate="2020-09-30 20:59:02 -0700" endDate="2020-09-30 20:59:02 -0700" value="67">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Ferris’s Apple Watch" sourceVersion="7.0.1" device="&lt;&lt;HKDevice: 0x000000000g&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,2, software:7.0.1&gt;" unit="count/min" creationDate="2020-09-30 20:59:04 -0700" startDate="2020-09-30 20:59:03 -0700" endDate="2020-09-30 20:59:03 -0700" value="67">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Ferris’s Apple Watch" sourceVersion="7.0.1" device="&lt;&lt;HKDevice: 0x000000000g&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,2, software:7.0.1&gt;" unit="count/min" creationDate="2020-09-30 20:59:04 -0700" startDate="2020-09-30 20:59:04 -0700" endDate="2020-09-30 20:59:04 -0700" value="68">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Ferris’s Apple Watch" sourceVersion="7.0.1" device="&lt;&lt;HKDevice: 0x000000000g&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,2, software:7.0.1&gt;" unit="count/min" creationDate="2020-09-30 20:59:06 -0700" startDate="2020-09-30 20:59:05 -0700" endDate="2020-09-30 20:59:05 -0700" value="71">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Ferris’s Apple Watch" sourceVersion="7.0.1" device="&lt;&lt;HKDevice: 0x000000000g&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,2, software:7.0.1&gt;" unit="count/min" creationDate="2020-09-30 20:59:06 -0700" startDate="2020-09-30 20:59:06 -0700" endDate="2020-09-30 20:59:06 -0700" value="73">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Ferris’s Apple Watch" sourceVersion="7.0.1" device="&lt;&lt;HKDevice: 0x000000000g&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,2, software:7.0.1&gt;" unit="count/min" creationDate="2020-09-30 20:59:08 -0700" startDate="2020-09-30 20:59:07 -0700" endDate="2020-09-30 20:59:07 -0700" value="72">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Ferris’s Apple Watch" sourceVersion="7.0.1" device="&lt;&lt;HKDevice: 0x000000000g&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,2, software:7.0.1&gt;" unit="count/min" creationDate="2020-09-30 20:59:08 -0700" startDate="2020-09-30 20:59:08 -0700" endDate="2020-09-30 20:59:08 -0700" value="72">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Ferris’s Apple Watch" sourceVersion="7.0.1" device="&lt;&lt;HKDevice: 0x000000000g&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,2, software:7.0.1&gt;" unit="count/min" creationDate="2020-09-30 20:59:10 -0700" startDate="2020-09-30 20:59:09 -0700" endDate="2020-09-30 20:59:09 -0700" value="70">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Ferris’s Apple Watch" sourceVersion="7.0.1" device="&lt;&lt;HKDevice: 0x000000000g&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,2, software:7.0.1&gt;" unit="count/min" creationDate="2020-09-30 20:59:10 -0700" startDate="2020-09-30 20:59:10 -0700" endDate="2020-09-30 20:59:10 -0700" value="67">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Ferris’s Apple Watch" sourceVersion="7.0.1" device="&lt;&lt;HKDevice: 0x000000000g&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,2, software:7.0.1&gt;" unit="count/min" creationDate="2020-09-30 20:59:12 -0700" startDate="2020-09-30 20:59:11 -0700" endDate="2020-09-30 20:59:11 -0700" value="67">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Ferris’s Apple Watch" sourceVersion="7.0.1" device="&lt;&lt;HKDevice: 0x000000000g&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,2, software:7.0.1&gt;" unit="count/min" creationDate="2020-09-30 20:59:12 -0700" startDate="2020-09-30 20:59:12 -0700" endDate="2020-09-30 20:59:12 -0700" value="67">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Ferris’s Apple Watch" sourceVersion="7.0.1" device="&lt;&lt;HKDevice: 0x000000000g&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,2, software:7.0.1&gt;" unit="count/min" creationDate="2020-09-30 20:59:14 -0700" startDate="2020-09-30 20:59:13 -0700" endDate="2020-09-30 20:59:13 -0700" value="69">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Ferris’s Apple Watch" sourceVersion="7.0.1" device="&lt;&lt;HKDevice: 0x000000000g&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,2, software:7.0.1&gt;" unit="count/min" creationDate="2020-09-30 20:59:14 -0700" startDate="2020-09-30 20:59:14 -0700" endDate="2020-09-30 20:59:14 -0700" value="70">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Ferris’s Apple Watch" sourceVersion="7.0.1" device="&lt;&lt;HKDevice: 0x000000000g&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,2, software:7.0.1&gt;" unit="count/min" creationDate="2020-09-30 20:59:16 -0700" startDate="2020-09-30 20:59:15 -0700" endDate="2020-09-30 20:59:15 -0700" value="70">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Ferris’s Apple Watch" sourceVersion="7.0.1" device="&lt;&lt;HKDevice: 0x000000000g&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,2, software:7.0.1&gt;" unit="count/min" creationDate="2020-09-30 20:59:16 -0700" startDate="2020-09-30 20:59:16 -0700" endDate="2020-09-30 20:59:16 -0700" value="70">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Ferris’s Apple Watch" sourceVersion="7.0.1" device="&lt;&lt;HKDevice: 0x000000000g&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,2, software:7.0.1&gt;" unit="count/min" creationDate="2020-09-30 21:00:44 -0700" startDate="2020-09-30 21:00:15 -0700" endDate="2020-09-30 21:00:15 -0700" value="74">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Ferris’s Apple Watch" sourceVersion="7.0.1" device="&lt;&lt;HKDevice: 0x000000000g&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,2, software:7.0.1&gt;" unit="count/min" creationDate="2020-09-30 21:05:39 -0700" startDate="2020-09-30 21:03:27 -0700" endDate="2020-09-30 21:03:27 -0700" value="72">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Ferris’s Apple Watch" sourceVersion="7.0.1" device="&lt;&lt;HKDevice: 0x000000000g&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,2, software:7.0.1&gt;" unit="count/min" creationDate="2020-09-30 21:10:59 -0700" startDate="2020-09-30 21:09:54 -0700" endDate="2020-09-30 21:09:54 -0700" value="72">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Ferris’s Apple Watch" sourceVersion="7.0.1" device="&lt;&lt;HKDevice: 0x000000000g&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,2, software:7.0.1&gt;" unit="count/min" creationDate="2020-09-30 21:15:59 -0700" startDate="2020-09-30 21:12:37 -0700" endDate="2020-09-30 21:12:37 -0700" value="72">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Ferris’s Apple Watch" sourceVersion="7.0.1" device="&lt;&lt;HKDevice: 0x000000000g&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,2, software:7.0.1&gt;" unit="count/min" creationDate="2020-09-30 21:17:47 -0700" startDate="2020-09-30 21:17:45 -0700" endDate="2020-09-30 21:17:45 -0700" value="72">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Ferris’s Apple Watch" sourceVersion="7.0.1" device="&lt;&lt;HKDevice: 0x000000000g&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,2, software:7.0.1&gt;" unit="count/min" creationDate="2020-09-30 21:21:25 -0700" startDate="2020-09-30 21:16:27 -0700" endDate="2020-09-30 21:16:27 -0700" value="73">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Ferris’s Apple Watch" sourceVersion="7.0.1" device="&lt;&lt;HKDevice: 0x000000000g&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,2, software:7.0.1&gt;" unit="count/min" creationDate="2020-09-30 21:26:18 -0700" startDate="2020-09-30 21:20:48 -0700" endDate="2020-09-30 21:20:48 -0700" value="73">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Ferris’s Apple Watch" sourceVersion="7.0.1" device="&lt;&lt;HKDevice: 0x000000000g&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,2, software:7.0.1&gt;" unit="count/min" creationDate="2020-09-30 21:30:58 -0700" startDate="2020-09-30 21:27:15 -0700" endDate="2020-09-30 21:27:15 -0700" value="72">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Ferris’s Apple Watch" sourceVersion="7.0.1" device="&lt;&lt;HKDevice: 0x000000000g&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,2, software:7.0.1&gt;" unit="count/min" creationDate="2020-09-30 21:36:11 -0700" startDate="2020-09-30 21:32:03 -0700" endDate="2020-09-30 21:32:03 -0700" value="73">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="1"/>
 </Record>